version: 2
updates:
  # Enable crate version updates for the main crate
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  # Enable version updates for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
