[package]
name = "kernel"
version = "0.6.1"
edition = "2024"
exclude = ["xtask"]

[features]
default = ["panic_traces"]
panic_traces = ["dep:rustc-demangle"]
buffered_uart = []

[dependencies]
bit_field = "0.10"
bitflags = "2.9"
elf = { version = "0.8.0", default-features = false }
getrandom = "0.3"
heapless = { version = "0.9", default-features = false, features = [
    "nightly",
    "mpmc_large",
] }
ioports = "1.0"
limine = { version = "0.5", features = ["uuid"] }
log = { version = "0.4", default-features = false }
num_enum = { version = "0.7", default-features = false }
rand_pcg = { version = "0.9", default-features = false }
safe-mmio = "0.2"
static_assertions = "1.1.0"
thiserror = { version = "2.0", default-features = false }
uart = { version = "3.0", default-features = false, features = [
    "address_impl",
] }
uuid = { version = "1.16", default-features = false, features = ["v4"] }

# source: git
# acpica = { git = "https://github.com/linuiz-project/acpica", tag = "v0.1.1" }
libsys = { git = "https://github.com/linuiz-project/libsys", tag = "v0.4.0" }

# feature-specific
rustc-demangle = { version = "0.1", optional = true } # feature: panic_traces

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "11.0"

[profile.dev]
panic = "abort"
opt-level = 0

[profile.release]
panic = "abort"
lto = true
opt-level = 2
codegen-units = 1
