[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-none"
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
    "-C", "embed-bitcode=yes"
]