[workspace]
members = [
    "apic",
    "bitslice",
    "bump",
    "freelist",
    "msr",
    "pic_8259",
    "port-rs",
    "slab",
    "slob",
    "uart",
    "vmem",
]

[profile.dev]
opt-level = 1