[unstable]
build-std = [
    "core",
    "compiler_builtins",
    "alloc",
]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "riscv64gc-unknown-none-elf"
rustflags = [
    "-C",
    "code-model=kernel",
    "-C",
    "embed-bitcode=yes",
]
