[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=--script=lds/x86_64-unknown-none.lds"]

[target.riscv64gc-unknown-none]
rustflags = ["-C", "link-arg=--script=lds/riscv64gc-unknown-none.lds"]
