on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Check and Lint

jobs:
  check:
    name: Check & Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src, rustfmt
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: check
      - uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: fmt -- --all --check

  check-xtask:
    name: Check xTask
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: xtask/
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check
